create table public.medical_records (
  id uuid not null default gen_random_uuid (),
  user_id uuid null,
  university_id character varying(50) null,
  last_name character varying(100) null,
  first_name character varying(100) null,
  middle_name character varying(50) null,
  sex character varying(20) null,
  birthday date null,
  age integer null,
  address text null,
  contact_no character varying(20) null,
  religion character varying(100) null,
  nationality character varying(100) null,
  civil_status character varying(50) null,
  emergency_name character varying(100) null,
  emergency_relation character varying(50) null,
  emergency_address text null,
  emergency_contact character varying(20) null,
  vax1 character varying(50) null,
  vax1_date date null,
  vax1_remarks text null,
  vax2 character varying(50) null,
  vax2_date date null,
  vax2_remarks text null,
  booster1 character varying(50) null,
  booster1_date date null,
  booster1_remarks text null,
  booster2 character varying(50) null,
  booster2_date date null,
  booster2_remarks text null,
  covid_history text null,
  other_medical_history text null,
  other_family_history text null,
  smoking character varying(10) null,
  smoking_details text null,
  alcohol character varying(10) null,
  alcohol_details text null,
  drugs character varying(10) null,
  drugs_details text null,
  questionnaire jsonb null default '{}'::jsonb,
  height character varying(20) null,
  weight character varying(20) null,
  bmi character varying(20) null,
  waist character varying(20) null,
  lmp character varying(20) null,
  lab_cbc character varying(50) null,
  lab_cbc_facility character varying(100) null,
  lab_cbc_date date null,
  lab_ua character varying(50) null,
  lab_ua_facility character varying(100) null,
  lab_ua_date date null,
  lab_xray character varying(50) null,
  lab_xray_facility character varying(100) null,
  lab_xray_date date null,
  physician character varying(100) null,
  exam_date date null,
  nurse_on_duty character varying(100) null,
  checked_medical jsonb null default '[]'::jsonb,
  checked_family jsonb null default '[]'::jsonb,
  checked_health jsonb null default '[]'::jsonb,
  vital_records jsonb null default '[]'::jsonb,
  status character varying(20) null default 'pending'::character varying,
  is_approved boolean null default false,
  student_signature character varying(255) null,
  date_signed date null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  approved_at timestamp with time zone null,
  finding1 text null,
  remarks text null,
  is_fit boolean null default true,
  is_normal_findings boolean null default true,
  constraint medical_records_pkey primary key (id),
  constraint medical_records_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_medical_records_status on public.medical_records using btree (status) TABLESPACE pg_default;

create index IF not exists idx_medical_records_university_id on public.medical_records using btree (university_id) TABLESPACE pg_default;

create index IF not exists idx_medical_records_user on public.medical_records using btree (user_id) TABLESPACE pg_default;