create table public.system_config (
  id bigint generated by default as identity not null,
  departments jsonb not null default '[]'::jsonb,
  non_academic_offices jsonb not null default '[]'::jsonb,
  clinic_roles jsonb not null default '[]'::jsonb,
  faculty_roles jsonb not null default '[]'::jsonb,
  admin_roles jsonb not null default '[]'::jsonb,
  classifications jsonb not null default '{}'::jsonb,
  job_titles jsonb not null default '{}'::jsonb,
  updated_at timestamp with time zone not null default now(),
  sections jsonb not null default '[]'::jsonb,
  password_rules jsonb null default '{"minLength": 8, "requireNumber": true, "requireLowercase": true, "requireUppercase": true, "requireSpecialCharacter": true}'::jsonb,
  staff_roles jsonb not null default '[]'::jsonb,
  prompt_student_academic_update boolean not null default false,
  academic_update_version integer not null default 1,
  constraint system_config_pkey primary key (id)
) TABLESPACE pg_default;