create table public.users (
  id uuid not null default gen_random_uuid (),
  uid character varying(128) null,
  email character varying(255) not null,
  password_hash character varying(255) null,
  first_name character varying(100) not null,
  middle_name character varying(100) null,
  last_name character varying(100) not null,
  suffix character varying(20) null,
  university_id character varying(50) null,
  role character varying(50) null default 'student'::character varying,
  is_verified boolean null default false,
  is_profile_setup boolean null default false,
  profile_complete boolean null default false,
  birthday date null,
  age integer null,
  sex character varying(20) null,
  blood_type character varying(10) null,
  home_address text null,
  religion character varying(100) null,
  nationality character varying(100) null,
  civil_status character varying(50) null,
  department character varying(100) null,
  program character varying(100) null,
  year_level character varying(20) null,
  section character varying(20) null,
  student_classification character varying(50) null,
  classification character varying(100) null,
  job_title character varying(100) null,
  phone_number character varying(20) null,
  emergency_contact jsonb null default '{}'::jsonb,
  vaccinations jsonb null default '{"dose1": {}, "dose2": {}, "booster1": {}, "booster2": {}}'::jsonb,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  constraint users_uid_key unique (uid),
  constraint users_university_id_key unique (university_id)
) TABLESPACE pg_default;